spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/agendafacil}
    username: ${DB_USER:agenda}
    password: ${DB_PASSWORD:agenda123}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true